Terminal crash fix
cs233/ubuntu-vnc-desktop-spimbot pull request #1
Opened 2023-04-13 20:26 UTC by philvukovic

* use `bash` everywhere
* move `update_spimbot.sh` to `.bashrc`
* fix exiting on error issue (`set -e` removed)
* added QtSpimbot in `~/bin` so that `QtSpimbot ...` works
* add auto image pull to run command

2023-04-14 01:56 UTC, Nydauron requested changes

2023-04-14 01:56 UTC, Nydauron commented on image/home/.bashrc
> +export PATH=$PATH:"/home/ubuntu/bin"
This line can be moved to here
https://github.com/cs233/ubuntu-vnc-desktop-spimbot/blob/a04ef98ef76cbd734aee821bf4dcaee58f773c1a/image/home/.bashrc#L12-L14

2023-04-14 01:56 UTC, Nydauron commented on image/home/.bashrc
Can we copy over the .bashrc currently in the container (the container has a default .bashrc for ubuntu) and put this into another file `.update_spimbot.sh` then add `source .update_spimbot.sh` to the `.bashrc` file?

2023-04-15 00:37 UTC, philvukovic commented on image/home/.bashrc
Yeah, good idea

2023-04-15 00:37 UTC, philvukovic commented on image/home/.bashrc
> +export PATH=$PATH:"/home/ubuntu/bin"
agree

2023-04-15 00:45 UTC, philvukovic commented on image/home/.bashrc
might require creating home directory explicitly though, needs a little testing

2023-04-15 22:16 UTC, Nydauron commented on image/home/.bashrc
> might require creating home directory explicitly though

This is probably not necessary. There already exists a `.bashrc` in the container

2023-04-18 00:25 UTC, philvukovic commented on image/home/.bashrc
> +export PATH=$PATH:"/home/ubuntu/bin"
fixed in latest

2023-04-18 00:26 UTC, philvukovic commented on image/home/.bashrc
changed to `echo [...] >> .bashrc` in Dockerfile

2023-04-18 00:53 UTC, Nydauron approved these changes

2023-04-18 01:07 UTC, merged